Fixed some of the codacy-bot errors, one of which was having teraslice-client-js in package.json twice.  That fixes the error TypeError: inUrl.indexOf is not a function in the ex list command.