Expand teraslice cli functionality (#843)
* added new commands to teraslice-cli and ex end point to teraslice-client-js

* Fixed incorrect function dir in asset and incorrect command directory in job.

* refactored assets to be in files for each command and updated tests

* fixed some errors in cjob cmds

* changed default output to txt instead of pretty

* removed test config file

* removed cluster names and exs id from comment in shorthand.js

* added asset init

* expanded asset init

* updated asset init

* updates to help, readme, and added -a to status

* small changes to test data

* updatd tests

* updated init tests

* finishing up ex commands and fixing some errors with cjob commands

* fixed node list output fielding for native and k8s clustering

* updated cjob and controller commands

- Added option to bypass prompts
- Added ability for cjob commands to execute on a single job or all jobs on a cluster

* Changed command references from tjm to earl.

* changed prompts version to 1.1.1

* updated yarn.lock file, old version had some terascope npm registry entries

* Fixed asset tests that were failing.

* Fixed some of the codacy-bot errors, one of which was having teraslice-client-js in package.json twice.  That fixes the error TypeError: inUrl.indexOf is not a function in the ex list command.

* making changes based on feedback.  Moved commands from singular to plural.

* removed asset tests that were moved to assets

* Moved alias to aliases. Removed tjm from package.json

* Made several changes based on usage feedback.
- Moved job command functionality into jobs commands.
- Improved command line error handling.
- Renamed commands to match teraslice api.
- Improved error handling.
- Updated assets commands to utilize cli configuration and cluster shorthand.

* jobs/save command didn't have command name spec'd in save.js

* Defined command that was missing in serveral commands.

* updated yarn.lock